---

- hosts: web

  become: yes
  become_user: root

  roles:
    - docker

  tasks:
    - name: docker network
      docker_network:
        name: foobar

    - name: nginx container
      docker_container:
        image: nginx
        state: started
        restart_policy: always
        restart_policy_retry: 3
        networks:
          - foobar
        ports:
          - 0.0.0.0:80:80
      tags:
        - deploy
