---

- name: Install kernel extras
  apt:
    name:
      - "linux-image-extra-{{ ansible_kernel }}"
      - "linux-image-extra-virtual"
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg-curl"
      - "software-properties-common"
    state: present
    update_cache: true
    cache_valid_time: 600

- name: Add gpg key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true
    state: present

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: true
    cache_valid_time: 600

- name: Install docker python library
  pip:
    name: "docker"
    version: "3.6.0"

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: true

- name: Enable the Docker daemon as a service and start it.
  systemd:
    name: docker
    state: started
    enabled: true

