---

- name: Install kernel extras
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add gpg key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add apt repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: Install docker
  apt:
    name: docker-engine
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install pip, python-dev package with apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - python-dev
    - python-pip

- name: Upgrade latest pip, setuptools, with pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools
#    - docker-py
    - docker-compose
    - PyYAML


# Workaround for https://github.com/ansible/ansible/issues/17495, should be
# fixed when ansible 2.2 is released, see
# https://github.com/ansible/ansible/commit/39aa740531f171a557e8604babd493793d63323e
# TODO: Remove when ansible 2.2 is released

- name: Install specific version of docker-py
  pip: name=docker-py version=1.9.0

- name: Start docker
  service:
    name: docker
    state: started
