---

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 600

- name: Install kernel extras
  apt:
    name:
      - "linux-image-extra-{{ ansible_kernel }}"
      - "linux-image-extra-virtual"
    state: present
  when: docker_install_kernel_extras

- name: Install system dependencies
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg-curl"
      - "software-properties-common"
      - "python-pip"
    state: present

- name: Add gpg key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true
    state: present

- name: Install docker with version {{ docker_ce_version|default("latest") }}
  apt:
    name: "docker-ce{% if docker_ce_version|default(None) %}={{ docker_ce_version }}*{% endif %}"
    state: present

- name: Install docker python library
  pip:
    name: "docker"
    version: "{{ docker_python_version }}"

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: true

- name: Enable the Docker daemon as a service and start it.
  systemd:
    name: docker
    state: started
    enabled: true
