---

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 600
    force_apt_get: true

- name: Install kernel extras
  apt:
    name:
      - "linux-image-extra-virtual"
    force_apt_get: true
    state: present
  when: docker_install_kernel_extras|bool

- name: Install common system dependencies
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg2"
      - "software-properties-common"
      - "python-pip"
    force_apt_get: true
    state: present

- name: Install on Ubuntu
  import_tasks: install_ubuntu.yml
  when: 
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install on Debian
  import_tasks: install_debian.yml
  when: 
    - ansible_facts['distribution'] == "Debian"

- name: Install docker with version {{ docker_ce_version|default("latest") }}
  apt:
    name: "docker-ce{% if docker_ce_version|default(None) %}={{ docker_ce_version }}*{% endif %}"
    force_apt_get: true
    state: present

- name: Install docker python library
  pip:
    name: "docker"
    version: "{{ docker_python_version }}"

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable the Docker daemon as a service and start it
  systemd:
    name: docker
    state: started
    enabled: true
