---

- name: Initialize swarm manager
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
  register: "swarm"
  notify:
    - restart docker
