---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu16
    image: ubuntu:16.04
    cap_add:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /sbin/init
    privileged: true
    groups:
      - docker_swarm_managers
  - name: ubuntu18
    image: ubuntu:18.04
    cap_add:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /sbin/init
    privileged: true
    groups:
      - docker_swarm_workers
  - name: extra_manager
    image: ubuntu:18.04
    cap_add:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /sbin/init
    privileged: true
    groups:
      - docker_swarm_managers
      - docker_swarm_workers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ubuntu16:
        docker_swarm_labels:
          one: manager
          second: label
    group_vars:
      docker_swarm_workers:
        docker_swarm_labels:
          a: worker
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
